### ISSUE TITLE
Change all Social Hackers Academy desciption as SHA, to avoid spamming messages

### ISSUE THREAD

**Issue by aggelinaml** [Marc-AntoineA/A2P#11]

**Comment by Marc-AntoineA** [comment]
Please be more precise in your description. I don't get the link between _Changing Social Hackers Academy as SHA_ and _avoiding spamming messages_

**Comment by aggelinaml** [comment]
Sometimes, server reads the "Hackers" on the email's subject or main body and it directly moves the mail to spams :/ That's why do not refer at all Social Hackers Academy. Add SHA and then refer only coding program/class.

**Comment by Marc-AntoineA** [comment]
It has to be done only in the subject, not in the body.
