### ISSUE TITLE
Do not use the e-mails for rejection as we cannot send them a feedback for every step they apply.

### ISSUE THREAD

**Issue by aggelinaml** [Marc-AntoineA/A2P#12]
We don't do it now, so we will not do it. 
It's extra admin work that we can't afford it. 
I think it's better to not use at all rejection message, but our team will process their steps and will contact them for feedback/comments etc.

**Comment by Marc-AntoineA** [comment]
Two possibilities, depending on the deadline:

- deactivate sending rejection emails ;

- allow the superviser to add a small feedback when he rejects the step (or when he accepts one, it's easier to do it for both situation), which is automatically added directly into the template.

**Comment by aggelinaml** [comment]
which is automatically added directly into the template: with this, you mean that the superviser will add some feedback comments and there comments will automatically be sent with an e-mail? Not sure it will work.. Generally my suggestion, according to our experience, is to not include rejection mail and the administrator on the interview stage can give sime feedback on the spot. Otherwise I am not sure it will work. 

The same is for accepting the steps. They might get confused as they might not understand they should move. We can have accept & reject the application, after the interview stage. We will not have someone loooking at these, we lack in HR you are aware of that!

Let's discuss it on Friday though!

**Comment by Marc-AntoineA** [comment]
For now, no changes on the website: an email without any feedback is sent when a superviser clicks on the accept or reject button. But the superviser can choose to click or not on this button.
