### ISSUE TITLE
Update the google form link in the "Have a small conversation with our team!" step to be clickable

### ISSUE THREAD

**Issue by ainulhamdani** [Marc-AntoineA/A2P#17]
I know that you will implement the form to the application. 
But I think for now it's better to make the link clickable.

**Comment by Marc-AntoineA** [comment]
There is a misunderstanding with Aggelina. It could already be clickable. For example, see the Khan Academy Step on the prod website.
In the process editor, any page caption (only them for now) can be html formatted. It means that if you write` <a href='...' target='_blank'>My link</a>`, it works.

The implemation of the google form could be done in the future as described in #3 but nothing is planned for now.
