### ISSUE TITLE
Cannot edit the content of the process that has been opened

### ISSUE THREAD

**Issue by ainulhamdani** [Marc-AntoineA/A2P#18]
After the process is opened, it cannot be edited.

**Comment by Marc-AntoineA** [comment]
This is definitely not a bug but a feature of the software. If a process is opened, it means that people can apply to the process. If you change the questions, it would a be a mess (some people with the previous process and some with the new one).

To avoid this, a process cannot be edited when it's opened. This is why you have a warning when you choose to open a process. 

If you really want to edit a process, you have to create a new one (just by clicking on 'create a copy of this process') and delete the previous one. If it's really a problem to do this small step, we could imagine to allow to re-draft a process if nobody applied. 

Please let me know.

**Comment by Marc-AntoineA** [comment]
This behavior is explained in the wiki
[Wiki](https://github.com/Marc-AntoineA/A2P/wiki).

Please reopen this issue if you want to add an easy way to reopen a process if nobody applied.
