### ISSUE TITLE
Birth Date

### ISSUE THREAD

**Issue by InigoMora** [Marc-AntoineA/A2P#23]
Birth date - birthdate formatting is tricky, this one is rather a calendar like. It has the default date of today filled (increases a chance to get wrong birthdate submitted). Perhaps it could have the format of blank -- and person selects day/month/date

(Viktorija)

**Comment by Marc-AntoineA** [comment]
Thanks Viktorija for you interesting remark. It will be blank by default by the next version (in the following days).
