### ISSUE TITLE
Open question word count

### ISSUE THREAD

**Issue by InigoMora** [Marc-AntoineA/A2P#24]
As noted, it could have word count for a person to know where they're at.
Also, it should not allow to submit less than a min amount of words.

(Viktorija)

**Comment by Marc-AntoineA** [comment]
Thank you Viktorija for your remarks:

- For the first one it could be done (just display the number of words) but it would be done every time you have a long text field (for example for the question _If you studied, what and where, and how long?_
- For the second point: it was originaly planned for the first version of the website. The idea was to add for both the motivation letter and the code pen website an automatic validation. By this, the superviser will check only valid motivation letters (more than X words) and valid code pen website (more than X title, use of css etc.). As the project was dead during few months, this feature wasn't developed. It could be developed in the next version if needed but it cannot be done for the next days as it's a big update (about two days of work).

What do you thing about it? Do you want do add it to the next version? (in September or October)

**Comment by Marc-AntoineA** [comment]
Update:
Words counter are now added in both superviser and applicant websites for every **long text** question. No hard limit on it.
* On **admin panel**:
![image](https://user-images.githubusercontent.com/27521221/61746914-07922600-ad9d-11e9-89b1-8299406f490a.png)
* On **applicant view** (cannot be edited in the screenshot as it has already been submitted)
![image](https://user-images.githubusercontent.com/27521221/61747079-68b9f980-ad9d-11e9-8fa2-601b7d1729d8.png)

Please tell me if you want to add the automatic validation later.
