### ISSUE TITLE
Remove "," from "Why we should choose you, as a student?"

### ISSUE THREAD

**Issue by InigoMora** [Marc-AntoineA/A2P#25]
Remove "," from "Why we should choose you, as a student?" from the "Please tell us, why you want to attend the class?" section. Also remove the "," from "Please tell us, why you want to attend the class?" tittle.

**Comment by Marc-AntoineA** [comment]
Thanks Inigo and Viktorija for your feedback.

Your remark is linked to the **data** of the website, (almost) everything relative to the **processes** can be edited in the administration panel. Therefore, I cannot do this modification and you should see with @aggelinaml  for the credentials of the administration panel.

Moreover, you can have a look to the wiki  [Wiki](https://github.com/Marc-AntoineA/A2P/wiki/Manage-a-recruitment-campaign) for more info about how the sofware works (I just wrote few lines).

**Comment by aggelinaml** [comment]
hey guys!
@Marc-AntoineA @InigoMora I am fixing it right now on the Admin panel! :)
