### ISSUE TITLE
Login page - Login button

### ISSUE THREAD

**Issue by InigoMora** [Marc-AntoineA/A2P#27]
AT the login page, the Login button says "Creat my profil!" instead of "Log in" or "Sign in"

**Comment by Marc-AntoineA** [comment]
Yes! Thanks for seeing it, I haven't seen this modification made by @aggelinaml. 
For information, you can do yourself this kind of modification by editing the file `applicant-frontend/src/static.json` (ask Aggelina for more info).

It should be already corrected on the dev version and on the prod one tonight, now it's written **Open my profile!**
