### ISSUE TITLE
Feature to be able to download applicants data from administrator

### ISSUE THREAD

**Issue by aggelinaml** [Marc-AntoineA/A2P#28]

**Comment by Marc-AntoineA** [comment]
Hi @aggelinaml, can you add more details about the data you want? Do you want to have it an excel file? Do you want directly the list of emails so you can invite them directly on Slack or send emails… 
If you want to download the data for all students at once or only for some of them.
Do you want also want to download their answers?

**Comment by aggelinaml** [comment]
Hey @Marc-AntoineA , We want an excel with all their data, in columns. Just one file with all their data and answer responses. Basically to not have trello again managing their applications, but just a large excel file! I would like to have this type of excel file:
https://docs.google.com/spreadsheets/d/1V2lWljBzAvaLbVR0bmrFPvy4pJ7pqUKhWrp3WKVW0IM/edit?usp=drive_web&ouid=103911066935246531601  but not only with their personal information but with their codepen website links!

Is it clear?

**Comment by Marc-AntoineA** [comment]
It's already available on the dev version (basic feature). If you want to do an export for the real data, please let me know and I can do it.
