### ISSUE TITLE
Reset pasword email

### ISSUE THREAD

**Issue by InigoMora** [Marc-AntoineA/A2P#31]
When using the "Forgot my password" option, the password gets reseted (or i believe as it doesn't let me use my old password), but I didn't receive an email to reset it or with my new password. I know my email still exist because if I try to create a new account with the same email, it shows me an error.

**Comment by Marc-AntoineA** [comment]
Thanks Inigo. This bug is due to the PR #13 and is present for many emails. Many subject emails templates are wrong.
It will be corrected soon.

Adding unit tests and integration tests should be the next big update in few months.
