### ISSUE TITLE
Create a custom email body/content when rejecting task

### ISSUE THREAD

**Issue by ainulhamdani** [Marc-AntoineA/A2P#35]
For now the system will send a template email when we reject a task. But it will be more useful if we can send an email with custom body/content. Because sometimes we want to explain why we are rejecting the task and everyone case is not always same.

**Comment by ainulhamdani** [comment]
I understand the reason @aggelinaml don't want to add the feedback function because of lack of HR person to do so as she stated on #12. But I still think this function will be useful. We can make it if the custom feedback is empty, it will send out the default email body/content.

**Comment by Marc-AntoineA** [comment]
Ok. I can add a small optional feedback paragraph.

**Comment by Marc-AntoineA** [comment]
Some design update.
![image](https://user-images.githubusercontent.com/27521221/65818388-6c408580-e211-11e9-9332-313d735b908b.png)
![image](https://user-images.githubusercontent.com/27521221/65818395-795d7480-e211-11e9-82ef-cd3b6c26c1d6.png)
