### ISSUE TITLE
Create a notification system for administration

### ISSUE THREAD

**Issue by ainulhamdani** [Marc-AntoineA/A2P#36]
I think the notification system will be important here. Because as the number of applicants grow, it will be hard to monitor all the applicant task progress.

**Comment by Marc-AntoineA** [comment]
Can you be more precise? I don't really understand which kind of notifications you want

**Comment by ainulhamdani** [comment]
It will look like notification on Facebook. Every time the applicant finish a task, a notification will show up in the administrator dashboard. So there will be a list of notifications that ordered by time it created. And if we click on it, it will bring us to the specific task, then mark the notification as read.
So this way we will know if there is something new happen in the applicant task progress.

**Comment by Marc-AntoineA** [comment]
Ok. You mean a list **on the website** of all things you have to do (steps you have to accept or to reject).
It could be done but it needs some work to do it in a correct and useful way. 

For now, I suggest you to sort the list of the applicants by the 'last modification date' - it should help you. Also when you have the logo **pending** it means that you have something to do. I was thinking that it was enough.

**Comment by ainulhamdani** [comment]
Yes, for now it is enough. But as I stated before, as the number of the applicants grow and maybe we have several campaign, it will quite hard to monitor those with just sorting the list of the applicants.

**Comment by Marc-AntoineA** [comment]
Do you not prefer a filter on the array (display only applicants where a HR action is needed) ? This filter would be accessible by one click and could be set by default ? (It's only because I'm not sure that it would be easier to deal with a big list of notifications, not because I want to make dev easier).

**Comment by ainulhamdani** [comment]
The main idea is to have one place to see all the changes that happened in the system. 

As for now, if we have several campaign, we have to go to each of them then sort and filter the list. Imagine if we have way more campaign.

I know it sounded like the notification will be a big list because the potential number of applicants. But the notification will not come simultaneously.  And it will more useful if we got the notification to tell us if there is something changed in the system rather than check the applicants list one by one.

**Comment by Marc-AntoineA** [comment]
Thanks for your idea. I should be able to propose to you a new feature before the 20th of August. I'll work on it after #28 (basic feature available on dev version) and #35
