### ISSUE TITLE
[Urgent] Show the the class location on the sign up step

### ISSUE THREAD

**Issue by ainulhamdani** [Marc-AntoineA/A2P#39]
![sha](https://user-images.githubusercontent.com/7234044/63773264-7bb37280-c8e3-11e9-899c-67f9e5cda5fe.PNG)

We should show the location of the class on the sign up form, so the applicant will not confuse

**Comment by Marc-AntoineA** [comment]
Resolved.
The label should be a unique identifier of the process. For example. _Athens - class 5_ or _Crete - class 6_ The location is only a way to filter the processes (all the processes for Athens, for Barcelona…).
I updated the wiki with this info (see https://github.com/Marc-AntoineA/A2P/wiki/Manage-a-recruitment-campaign).

**Comment by Marc-AntoineA** [comment]
_Athens - class 5_
