### ISSUE TITLE
How can we un-reject existing applicants on the platform?

### ISSUE THREAD

**Issue by aggelinaml** [Marc-AntoineA/A2P#60]
It's difficult to manage the new applicants on the platform, as many offline accepted students are not online accepted, meaning that they have some steps rejected, no idea why & how that happened? So, can we & if we can, how to un-reject steps from students' applications, in order to officially accept them & pass them on the platform, under this certain label In this way the filtering will be much better & easier! I am also asking as it will be usefull for next applications' process

**Comment by Marc-AntoineA** [comment]
No. It's not possible right now except by editing the database manually. I can give you the credentials if you want to do it. 

With issue #45, it will possible to _unreject_ students or to edit their answers yourself (for example if they sent to you the code pen website). 

This feature is planned after the next ones, namely: issues #3, #55 and #56

**Comment by aggelinaml** [comment]
I see! Ok, better send the creds to us so we can do it manually then :)
