### ISSUE TITLE
Do rejected students still receive reminders on the e-mails?

### ISSUE THREAD

**Issue by aggelinaml** [Marc-AntoineA/A2P#61]
Do rejected students still receive reminders on the e-mails?

**Comment by Marc-AntoineA** [comment]
No.
The code for _reminders_ is defined in file `backend/schedulers/reminder_emails.js`. 

A reminder is sent to any student that fit all these points at midnight every Monday and Tuesday:
- He is in status _pending_, it means not _rejected_ and not _accepted_ ;
- He (or the supervisor) didn't update his account during the last 7 days ;
- The process is still opened (it means that deadline has not passed) ;
- At least one of its steps is in status _rejected_ or _todo_, _i.e._ the student has to do something on the plateform ;
- The student is not _archived_, _i.e_ he chooses to continue his application.

**Comment by aggelinaml** [comment]
Ok great! :)
