### ISSUE TITLE
How can we edit the feedback templates on the applicants' front-end? Abed has some additions on the feedback he will send!

### ISSUE THREAD

**Issue by aggelinaml** [Marc-AntoineA/A2P#63]
@abdalrahmanhamami here is your involvment as well!

**Comment by Marc-AntoineA** [comment]
All the emails templates can be edited directly through the _template online editor_ in the administrator panel. Moreover, they can be edited on the fly specifically for each applicant.

All the texts in the applicants frontend can be edited through the `applicant-frontend/src/static.json` file.

**Comment by aggelinaml** [comment]
Ok! Great! @abdalrahmanhamami fyi!
