### ISSUE TITLE
Add a button to all the parts of the platform, that will take students to the home page with the overview of the application process. Now it happes but they have to push the SHA logo, without knowing it!

### ISSUE THREAD

**Issue by aggelinaml** [Marc-AntoineA/A2P#9]

**Comment by Marc-AntoineA** [comment]
> Add a button to all the parts of the platform, that will take students to the home page with the overview of the application process. Now it happes but they have to push the SHA logo, without knowing it!

Do you want to save the answers when you click on it? Isn't it already the role of the save button, which is available on every page?

**Comment by aggelinaml** [comment]
No not save. Keep the save button as it is, but it's an idea to have a button at a specific place in the platform, always there, to go back to the main page. When they press submit, they also go directly on the home page with the steps, right?

**Comment by Marc-AntoineA** [comment]
At the beginning, we just keep the _save button_. We will see later to eventually add this button if it's needed or not.

**Comment by Marc-AntoineA** [comment]
As written in #16, when the step cannot be edited (pending or accepted status), no buttons are presents.
